"""add AI classification confidence

Revision ID: 0ad9332bde8c
Revises: 580854c3824d
Create Date: 2026-09-25 17:56:56.405970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad9332bde8c'
down_revision: Union[str, Sequence[str], None] = '580854c3824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('category_confidence', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('priority_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'priority_confidence')
    op.drop_column('complaints', 'category_confidence')
    # ### end Alembic commands ###
