"""add AI department classification

Revision ID: 0f8388415035
Revises: 0ad9332bde8c
Create Date: 2026-09-25 19:21:31.378100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8388415035'
down_revision: Union[str, Sequence[str], None] = '0ad9332bde8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('department_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'department_confidence')
    op.drop_column('complaints', 'department')
    # ### end Alembic commands ###
