"""add password reset fields

Revision ID: 431bdb666b12
Revises: 30c4cc6211a3
Create Date: 2026-09-26 12:47:51.687213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431bdb666b12'
down_revision: Union[str, Sequence[str], None] = '30c4cc6211a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
