"""add notifications

Revision ID: df9385a34281
Revises: aff46901b504
Create Date: 2026-09-21 22:48:49.206675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df9385a34281'
down_revision: Union[str, Sequence[str], None] = 'aff46901b504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('responded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('complaint_responses_complaint_id_fkey')),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], name=op.f('complaint_responses_responded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('complaint_responses_pkey'))
    )
    op.create_index(op.f('ix_complaint_responses_id'), 'complaint_responses', ['id'], unique=False)
    op.create_table('complaint_status_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('new_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('complaint_status_history_changed_by_fkey')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('complaint_status_history_complaint_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('complaint_status_history_pkey'))
    )
    op.create_index(op.f('ix_complaint_status_history_id'), 'complaint_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_complaint_status_history_complaint_id'), 'complaint_status_history', ['complaint_id'], unique=False)
    # ### end Alembic commands ###
